### ISSUE TITLE
Nodle Arcadia finalization stalling at 140798

### ISSUE THREAD

**Issue by emielvanderhoek** [NodleCode/chain#28]
**Describe the bug**
Finalization is stalling on Nodle Arcadia network at block 140798. 
This could be related to Grandpa finality or changes to the validator set.

**To Reproduce**
1. Go to 'Telemetry: https://telemetry.polkadot.io/#list/Arcadia%20Nodle%20Network'
2. Add column 'Finalized Block'
3. See error

![image](https://user-images.githubusercontent.com/14069142/78760611-b4d7b900-7981-11ea-880a-6b28240700b7.png)

**Expected behavior**
The finalized block should be only a limited number of blocks behind chaintip under normal network conditions.

**Current behavior**
Finalization is stalled at 3 April 2018 at block 140798
Polkascan: https://polkascan.io/pre/nodle-arcadia/block/140798

**System (please complete the following information):**
 - N/A this is related to the blockchain network itself.

**Comment by ETeissonniere** [comment]
Seems like we are having an authority set issue, we could have hard forked the network to fix this but sadly we don't have access to the code to do so as we are on `alpha.3`. All things taken in consideration it seems like a good opportunity to restart the network to `alpha.5` in order to keep track with the changes on parity's side.

I am currently finishing the deployment on our side, would it be possible to restart the ingestion process on your side once it is done?

**Comment by ETeissonniere** [comment]
Seems like things are running fine on the new network (that actually runs `alpha.6`)
