### ISSUE TITLE
Support Polkadot Generic Ledger App

### ISSUE THREAD

**Issue by johnkennyuk** [NodleCode/chain#874]
I wanted to ask when will the nodle parachains metadata be updated? I am itching to use the ledger migration app to access my legacy app funds that have been inaccessible for ages also metadata issue?  But I am hoping the parachain will be updated soon to integrate with the ledger migration app asap?

I followed the early documentation and sent my nodl to my ledger for cold storage, but then the ledger app dev halted meaning I lost access to my funds from lack of app updates. Granted I realise it was in partnership with zondax and a familiar problem with polkadot chains which is supposedly why the generic polkadot app has been released, anyway the last thing I want to do is follow recent documentation suggestions recommending using the seed phrase to import the wallet to another client!

**Comment by aliXsed** [comment]
@johnkennyuk we are already in the process of updating our chain which as a side effect would enable Ledger polkadot generic app. The upgrade itself could be ready in a matter of 1 to 2 weeks. However due to the strict time consuming tests that any chain upgrade needs to go through, we would need to wait an additional 2 weeks to have that fully enabled on chain.

**Comment by johnkennyuk** [comment]
> @johnkennyuk we are already in the process of updating our chain which as a side effect would enable Ledger generic app for Polkadot parachains. The upgrade itself could be ready in a matter of 1 to 2 weeks. However due to the strict time consuming tests that any chain upgrade needs to go through, we would need to wait an additional 2 weeks to have that fully enabled on chain.

Excellent news, I appreciate your reply.

**Comment by aliXsed** [comment]
The very latest upgrade of the[ test-net](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fnode-6957502816543653888.lh.onfinality.io%2Fws%3Fapikey%3D09b04494-3139-4b57-a5d1-e1c4c18748ce#/explorer) (spec 32) successfully enabled Polkadot (generic) Ledger App. This version will be soon rolled out to our main-net too. If you have a Ledger device with an updated polkadot app, you can give it a test.
NOTE: Your polkadot ledger accounts are not going to be the same accounts as your previous nodle ledger accounts. While this upgrade enables you to use your polkadot ledger accounts to sign transactions and hold NODLs, this is not useful for accessing NODL tokens in your old hw wallet accounts.
Here is a test flow if you want to have a step by step guide:
Update Polkadot app on your Ledger
Use Talisman as your wallet and add your Polkadot Ledger accounts to your Talisman wallet
On Talisman settings go to Manage networks&tokens > Polkadot > find Nodle testnet > edit your Nodle testnet > tick the check for “CheckMetaDataHash is enabled”
From any accounts that you have on the testnet (like those equivalent to your mainnet accounts) transfer some notNodl tokens to you Polkadot Ledger accounts.
Now try to transfer funds from your Polkadot Ledger accounts to any other account.
Talisman will connect to your Ledger and send the metadata of the transaction to your Ledger for you to approve.
Approve the transaction on Ledger and enjoy it :slightly_smiling_face:

**Comment by aliXsed** [comment]
@johnkennyuk I haven't tested it myself but I do not expect that the Polkadot Migration app allows you to access your Nodle's Legacy Ledger accounts. It's because Ledger creates different wallets (out of the master wallets) for different chains. So Polkadot Migration should be suitable for accessing legacy Polkadot Ledger accounts. However I appreciate if you actually test it and let us know. 
The workaround that I have tested myself to get access to a Legacy Nodle Ledger account is this:
* Read this guideline first:
https://docs.astar.network/docs/use/manage-wallets/restore-ledger/
* In the step it suggests you choose Astar you should go for Nodle instead. While you are doing that you would have a couple of test points suggesting you are doing it correctly:
1. When you enter your mnemonic fully, you would see valid looking address/account appears on top of the “add an account form”
2. If you have entered the correct Ledger mnemonics then under the advanced creation options of the “add an account form”, you get the option of “Ledger (ed25519, BIP32 derivation)” in the drop box for “”keypair crypto type”)
3. If you have stored your account details in a place like Ledger Live App, you can then check the account address is matching that.
4. And the ultimate test is the token level or your balance in that account which should match your expectation.
You need to be very careful when handling your secret phrase. Make sure you would be only entering your mnemonic phrase in https://polkadot.js.org/apps or [nodleprotocol.io](http://nodleprotocol.io/) . After loading that page and for extra security you can even disconnect from the internet. That web page after it’s loaded wouldn’t need an online connection to work. You would only need your internet connection later and after you have restored your account. This process is inherently less secure than keeping you phrase always in a cold/offline way. So please do it on a computer that you trust and potentially remove that account later (especially if you have created a json file out of your wallet).
You should be able to do the exact same procedure inside polkadot.js extension or other wallets for your browser (if you have that) which could be a slightly better way of keeping your account then after. Better compared with the json wallet file.

**Comment by johnkennyuk** [comment]
I have tested with the migration app, it does allow you to see the balance of Nodl but again it fails on a slightly different error thus time a digest metadata failure, according to the docs for the ledger migration app parachains need there metadata to be update which then will allow the migration app to function in place of the old legacy chain apps such as the ledger nodle app.

I was sure someone mentioned nodle was getting a metadata update soon but from what I can tell still hasn't happened, although I do know the validation process for polkadot parachains is quite lengthy.

As to using aster I am against using Mnemonic from my ledge as it defeats the point of a cold wallet, but I have been toying around with nodle on the hydration and moonbean parachains which according to nova and aubwallet work with Nodl although I've not had any progress on that front,

I'm back to hoping the nodle parachain gets it's metadata updated at some point although it's starting to seem more and more unlike since the  ZkSync migration.

It is anoying though as back when I sent Nodl to my ledger for cold storage it was then officially supported wallet to use with Nodl but that was ages ago, as long as the parachain gets metadata updates made migration from to the new ledger generic polkadot app will be possible even without the Legacy ledger noddle app.

**Comment by aliXsed** [comment]
@johnkennyuk We are involving Zondax to see if they can offer a migration support here.

**Comment by aliXsed** [comment]
@johnkennyuk the main-net is upgraded we have reports that the Polkadot Migration App is working fine with it. Please see if your issue is now resolved.
